name: Webpack and deployment to github pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Build
      run: |
        npm install
        npx webpack
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.5.0
      if: success()
      with:
        target_branch: gh-pages
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
